server.port: 10020
#eureka.client.serviceUrl.defaultZone: http://localhost:1111/eureka/

#spring.cloud.config.server.git.uri: file:///Users/congsl/work/self/SpringCloudExamples/ConfigCenter/config.git #Error
spring.cloud.config.server.git.uri: file:///Users/congsl/work/self/SpringCloudExamples/config
spring.cloud.config.server.git.searchPaths: config/crm
#spring.cloud.config.server.git.username: username
#spring.cloud.config.server.git.password: password