logging:
  level:
    root: info
  file: access.log
spring.boot.admin.url: http://localhost:8088
server:
  undertow: #3000+
    io-threads: 60
    worker-threads: 10
#management.security.enabled: false